// Export all schemas from a central location
export * from './common';
export * from './auth';
export * from './servers';

// Export admin schemas with specific names to avoid conflicts
export {
  SystemConfigSchema,
  UpdateSystemConfigSchema,
  SystemStatsSchema,
  SystemStatsResponseSchema,
  AdminUserListQuerySchema,
  AdminUserResponseSchema,
  AdminUserListResponseSchema,
  AdminServerListQuerySchema,
  AdminServerResponseSchema,
  AdminServerListResponseSchema,
  AdminBackupListQuerySchema,
  AdminBackupResponseSchema,
  AdminBackupListResponseSchema,
  AdminLogListQuerySchema,
  AdminLogResponseSchema,
  AdminLogListResponseSchema,
  MaintenanceTaskSchema,
  MaintenanceTaskResponseSchema,
  type SystemConfig,
  type UpdateSystemConfigRequest,
  type SystemStats,
  type SystemStatsResponse,
  type AdminUserListQuery,
  type AdminUserResponse,
  type AdminUserListResponse,
  type AdminServerListQuery,
  type AdminServerResponse,
  type AdminServerListResponse,
  type AdminBackupListQuery,
  type AdminBackupResponse,
  type AdminBackupListResponse,
  type AdminLogListQuery,
  type AdminLogResponse,
  type AdminLogListResponse,
  type MaintenanceTaskRequest,
  type MaintenanceTaskResponse
} from './admin';

// Contract validation schemas
export {
  IdParamSchema,
  UserIdParamSchema,
  ServerIdParamSchema,
  AuthLoginContractSchema,
  AuthRegisterContractSchema,
  AuthChangePasswordContractSchema,
  ServerCreateContractSchema,
  ServerUpdateContractSchema,
  ServerBackupContractSchema,
  AdminCreateUserContractSchema,
  AdminUpdateUserContractSchema,
  AdminSystemConfigContractSchema,
  PaginationQuerySchema,
  ServerListQuerySchema,
  UserListQuerySchema,
  AuthResponseContractSchema,
  ServerResponseContractSchema,
  ServerListResponseContractSchema,
  UserResponseContractSchema,
  UserListResponseContractSchema,
  SystemConfigResponseContractSchema,
  SystemStatsResponseContractSchema,
  ErrorResponseContractSchema,
  type IdParam,
  type UserIdParam,
  type ServerIdParam,
  type AuthLoginContract,
  type AuthRegisterContract,
  type AuthChangePasswordContract,
  type ServerCreateContract,
  type ServerUpdateContract,
  type ServerBackupContract,
  type AdminCreateUserContract,
  type AdminUpdateUserContract,
  type AdminSystemConfigContract,
  type PaginationQuery,
  type ServerListQuery,
  type UserListQuery,
  type AuthResponseContract,
  type ServerResponseContract,
  type ServerListResponseContract,
  type UserResponseContract,
  type UserListResponseContract,
  type SystemConfigResponseContract,
  type SystemStatsResponseContract,
  type ErrorResponseContract
} from './contractValidation';

// Re-export commonly used Zod utilities
export { z } from 'zod';
