active_card: CARD-050
breadcrumb:
  step: 'CARD-049 - Fix backup API access control test expectations'
  last_commit: 'fix: [CARD-049] Fix backup API access control test expectations'
  next_action: 'CARD-050 - Next task in queue'
queue: [CARD-050, CARD-051, CARD-052, CARD-053]
  