active_card: null
breadcrumb:
  step: 'CARD-056 - Add memory bar gauge HTML structure to admin template'
  last_commit: 'feat: [CARD-056] Add memory bar gauge HTML structure to admin template'
  next_action: 'CARD-057 - Add system CPU utility function for admin configuration'
queue: 
  - CARD-057
  - CARD-058
  - CARD-059
  - CARD-060
  - CARD-061
  - CARD-062
  - CARD-063
  - CARD-064
  - CARD-065
  - CARD-066
  - CARD-067
  - CARD-068
  - CARD-069
  - CARD-070
  