active_card: CARD-091
breadcrumb:
  step: 'CARD-090 - Fix mock configuration and process verification issues'
  last_commit: 'fix: [CARD-090] Fix mock configuration and process verification issues'
  next_action: 'CARD-091 - Ready to start next task'
queue:
  - CARD-091
  - CARD-092
  - CARD-093
  - CARD-094
  - CARD-095
  - CARD-096
  - CARD-097
  - CARD-098
  - CARD-099
  - CARD-100
  - CARD-101
  