active_card: CARD-101
breadcrumb:
  step: 'CARD-100 - Add pytest options passthrough and advanced test execution features'
  last_commit: 'feat: [CARD-100] Add pytest options passthrough and advanced test execution features'
  next_action: 'CARD-101 - Ready to start next task'
queue:
  - CARD-101
  