active_card: null
breadcrumb:
  step: 'CARD-076 - Add conditional console/manage button to home template'
  last_commit: 'feat: [CARD-076] Add conditional console/manage button to home template'
  next_action: 'CARD-077 - Next card in queue'
queue: 
  - CARD-077
  - CARD-078
  - CARD-079
  - CARD-080
  - CARD-081
  - CARD-082
  - CARD-083
  - CARD-084
  - CARD-085
  - CARD-086
  