active_card: CARD-004
breadcrumb:
  step: 'CARD-003 completed - requirements.txt organized with pinned versions and categorized comments'
  last_commit: 'feat: [CARD-003] Pin all dependencies to specific versions in requirements.txt'
  next_action: 'Start at CARD-004'
queue:
  - CARD-004
  - CARD-005
  - CARD-006
  - CARD-007
  - CARD-008
  - CARD-009
  - CARD-010
  - CARD-011
  - CARD-012
  - CARD-013
  - CARD-014
  - CARD-015
  - CARD-016
  - CARD-017
  - CARD-018
  - CARD-019
  - CARD-020
  - CARD-021
  - CARD-022
  - CARD-023
