# Pre-commit configuration for mcServerManager
# Comprehensive hooks for Python, JavaScript/TypeScript, Shell, and general code quality

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '^.*\.(md|txt|json|yaml|yml)$'
      - id: end-of-file-fixer
        exclude: '^.*\.(md|txt|json|yaml|yml)$'
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  # Python-specific hooks
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=100', '--target-version=py311']
        exclude: '^venv/|^node_modules/|^\.venv/'

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length=100']
        exclude: '^venv/|^node_modules/|^\.venv/'

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--extend-ignore=E203,W503,E501,F401']
        exclude: '^venv/|^node_modules/|^\.venv/'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: ['--ignore-missing-imports', '--no-strict-optional']
        exclude: '^venv/|^node_modules/|^\.venv/|^tests/'

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        additional_dependencies: [pbr]
        args: ['-s', 'B101', '-x', 'tests/,venv/,node_modules/,.venv/,__pycache__,.pytest_cache,.mypy_cache', '--exit-zero']
        exclude: '^venv/|^node_modules/|^\.venv/|^tests/'

  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: python scripts/safety_check.py
        language: system
        files: requirements\.txt$
        exclude: '^venv/|^node_modules/|^\.venv/'

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ['--convention=google', '--add-ignore=D100,D101,D103,D104,D105,D107,D200,D205,D209,D212,D415']
        exclude: '^venv/|^node_modules/|^\.venv/|^tests/'

  # JavaScript/TypeScript hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [javascript, jsx, ts, tsx, json, css, scss, html, markdown]
        exclude: '^node_modules/|^venv/|^\.venv/'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: '^node_modules/|^venv/|^\.venv/'
        additional_dependencies:
          - eslint@8.56.0
          - '@typescript-eslint/eslint-plugin@6.19.1'
          - '@typescript-eslint/parser@6.19.1'
          - 'eslint-plugin-react@7.33.2'
          - 'eslint-plugin-react-hooks@4.6.0'

  # Shell script validation
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: ['--severity=warning']
        exclude: '^venv/|^node_modules/|^\.venv/'

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-4
    hooks:
      - id: shfmt
        args: ['-i', '2', '-ci', '-sr']



# Global configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: '3.0.0'

# Exclude patterns for generated files and dependencies
exclude: |
  (?x)^(
    venv/.*|
    node_modules/.*|
    \.venv/.*|
    \.git/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    \.coverage.*|
    \.mypy_cache/.*|
    \.bandit.*|
    \.secrets\.baseline.*|
    dist/.*|
    build/.*|
    \.eggs/.*|
    \.tox/.*|
    \.env.*|
    \.DS_Store.*|
    Thumbs\.db.*
  )$
