"""Initial migration with User, Server, and Configuration models

Revision ID: 3fd45cc77abb
Revises:
Create Date: 2025-09-13 00:58:50.429670

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3fd45cc77abb"  # pragma: allowlist secret
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("configuration", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.drop_index(batch_op.f("idx_config_key"))
        batch_op.drop_index(batch_op.f("idx_config_updated_at"))
        batch_op.drop_index(batch_op.f("idx_config_updated_by"))

    with op.batch_alter_table("server", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_server_memory"))
        batch_op.drop_index(batch_op.f("idx_server_name"))
        batch_op.drop_index(batch_op.f("idx_server_owner"))
        batch_op.drop_index(batch_op.f("idx_server_port"))
        batch_op.drop_index(batch_op.f("idx_server_status"))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("is_admin", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.drop_index(batch_op.f("idx_user_email"))
        batch_op.drop_index(batch_op.f("idx_user_is_active"))
        batch_op.drop_index(batch_op.f("idx_user_is_admin"))
        batch_op.drop_index(batch_op.f("idx_user_username"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_user_username"), ["username"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_user_is_admin"), ["is_admin"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_user_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_user_email"), ["email"], unique=False)
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("is_admin", existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table("server", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_server_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("idx_server_port"), ["port"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_server_owner"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_server_name"), ["server_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_server_memory"), ["memory_mb"], unique=False
        )

    with op.batch_alter_table("configuration", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_config_updated_by"), ["updated_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_config_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_config_key"), ["key"], unique=False)
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=False)

    # ### end Alembic commands ###
