"""Add backup_schedules table

Revision ID: 43724f018cc4
Revises: 3fd45cc77abb
Create Date: 2025-09-13 16:13:25.055671

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "43724f018cc4"
down_revision = "3fd45cc77abb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table already exists before creating it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    tables = inspector.get_table_names()

    if "backup_schedule" not in tables:
        op.create_table(
            "backup_schedule",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("server_id", sa.Integer(), nullable=False),
            sa.Column("schedule_type", sa.String(length=20), nullable=False),
            sa.Column("schedule_time", sa.Time(), nullable=False),
            sa.Column("retention_days", sa.Integer(), nullable=False),
            sa.Column("enabled", sa.Boolean(), nullable=False),
            sa.Column("last_backup", sa.DateTime(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(
                ["server_id"],
                ["server.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.CheckConstraint(
                "schedule_type IN ('daily', 'weekly', 'monthly')", name="check_schedule_type_values"
            ),
            sa.CheckConstraint("retention_days >= 1", name="check_retention_days_minimum"),
            sa.CheckConstraint("retention_days <= 365", name="check_retention_days_maximum"),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backup_schedule")
    # ### end Alembic commands ###
