"""Update experimental features - remove dummy features and add server management page

Revision ID: d4e5f6a7b8c9
Revises: c803b5d807c4
Create Date: 2025-09-14 09:52:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d4e5f6a7b8c9"
down_revision = "c803b5d807c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove dummy experimental features
    op.execute(
        """
        DELETE FROM experimental_feature
        WHERE feature_key IN ('advanced_monitoring', 'auto_backup', 'multi_user', 'plugin_manager')
        """
    )

    # Add the server_management_page feature
    op.execute(
        """
        INSERT INTO experimental_feature
        (feature_key, feature_name, description, enabled, is_stable, created_at, updated_at)
        VALUES
        ('server_management_page', 'Server Management Page',
         'Enhanced server management interface with real-time console and advanced controls',
         true, false, datetime('now'), datetime('now'))
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove the server_management_page feature
    op.execute(
        """
        DELETE FROM experimental_feature
        WHERE feature_key = 'server_management_page'
        """
    )

    # Restore dummy experimental features
    op.execute(
        """
        INSERT INTO experimental_feature
        (feature_key, feature_name, description, enabled, is_stable, created_at, updated_at)
        VALUES
        ('advanced_monitoring', 'Advanced Monitoring',
         'Enhanced monitoring capabilities with detailed metrics and alerts',
         false, false, datetime('now'), datetime('now')),
        ('auto_backup', 'Auto Backup',
         'Automatic backup scheduling and management for servers',
         false, false, datetime('now'), datetime('now')),
        ('multi_user', 'Multi-User Support',
         'Support for multiple users with role-based access control',
         false, false, datetime('now'), datetime('now')),
        ('plugin_manager', 'Plugin Manager',
         'Plugin management system for server extensions and mods',
         false, false, datetime('now'), datetime('now'))
        """
    )
    # ### end Alembic commands ###
