id: CARD-073
title: Update admin config handler to manage server management page feature
epic: Epic 1 – Server Management Page Implementation
sprint: 09-2025_SPRINT_3
status: todo
owner: cursor
links: []
acceptance:
  - Code compiles, lints, tests pass
  - Feature behind a flag if risky
  - Update planning/meta/PROJECT_HISTORY.md with log entry
  - Update meta/PROJECT_STATUS.md with one-liner
  - Commit follows Conventional Commits with [CARD-ID]
artifacts: []
notes: |
  Update the admin_config() function in app/routes/auth_routes.py to handle the server_management_page 
  feature toggle. Use the existing toggle_experimental_feature() utility function. Ensure the form 
  processing includes the new feature checkbox and properly updates the database.

