id: CARD-080
title: Implement server command execution system
epic: Epic 1 – Server Management Page Implementation
sprint: 09-2025_SPRINT_3
status: todo
owner: cursor
links: []
acceptance:
  - Code compiles, lints, tests pass
  - Feature behind a flag if risky
  - Update planning/meta/PROJECT_HISTORY.md with log entry
  - Update meta/PROJECT_STATUS.md with one-liner
  - Commit follows Conventional Commits with [CARD-ID]
artifacts: []
notes: |
  Add execute_server_command(server_id, command) function to app/utils.py. Function should:
  - Validate server is running before executing commands
  - Execute command via process input to the running server
  - Return execution result with success/error status
  - Include input validation and sanitization
  - Log all command executions for security
  - Handle errors gracefully with proper error messages

