id: CARD-061
title: Add experimental features route for admin toggles
epic: Epic 3 – Admin Configuration Enhancements
sprint: 09-2025_SPRINT_3
status: todo
owner: cursor
links: [CARD-060]
acceptance:
  - Code compiles, lints, tests pass
  - Feature behind a flag if risky
  - Update planning/meta/PROJECT_HISTORY.md with log entry
  - Update meta/PROJECT_STATUS.md with one-liner
  - Commit follows Conventional Commits with [CARD-061]
artifacts: []
notes: |
  Add new route @auth_bp.route("/admin_config/experimental", methods=["POST"]) in 
  app/routes/auth_routes.py to handle experimental feature toggle requests. Include 
  admin-only access, CSRF protection, input validation, and JSON response with 
  success/error status.
