id: CARD-097
title: Add test class and function execution capability to dev.sh
epic: Epic 3 – Test Suite Stabilization
sprint: 09-2025_SPRINT_3
status: todo  # todo | doing | review | done | blocked
owner: cursor
links: []
acceptance:
  - Code compiles, lints, tests pass
  - Feature behind a flag if risky
  - Update planning/meta/PROJECT_HISTORY.md with log entry
  - Update meta/PROJECT_STATUS.md with one-liner
  - Commit follows Conventional Commits with [CARD-ID]
artifacts: []
notes: |
  **Problem**: Agents need to run entire test files when they only want to test specific classes or functions within a file.
  
  **Solution**: Add --class and --function options to dev.sh test command for granular test execution.
  
  **Implementation Details**:
  1. Add --class and --function options to test command argument parsing
  2. Extend run_tests() function to handle class and function parameters
  3. Support pytest syntax: file::Class and file::Class::function
  4. Add validation to ensure test class/function exists
  5. Update help documentation with examples
  
  **New Usage Examples**:
  - `./dev.sh test --file tests/unit/test_server_management.py --class TestServerManagementRouteAccessControl`
  - `./dev.sh test --file tests/unit/test_server_management.py --class TestServerManagementRouteAccessControl --function test_validate_server_access_owner_user`
  - `./dev.sh test --file test_server_management.py --class TestConsoleAPIEndpoints`
  
  **Files to Modify**:
  - dev.sh (main script file)
  - Update show_usage() function with new examples
  - Extend run_tests() function to build pytest path from file/class/function
  - Update argument parsing in main() function
  
  **Technical Requirements**:
  - Build proper pytest path: file::Class::function
  - Validate that class/function exists (use pytest --collect-only for validation)
  - Support partial paths (just class name, just function name)
  - Provide clear error messages for invalid classes/functions
  - Maintain compatibility with existing options
